module.exports={
    userFormateError:{
        code:"10001",
        message:"用户名或密码为空",
        result:""
    },
    userAlreadyExists:{
        code:"10002",
        message:"用户名已存在",
        result:""
    },
    userCreateDefeated:{
        code:"10003",
        message:"用户创建失败",
        result:""
    },
    UserDoesNotExist:{
        code:"10004",
        message:"用户不存在",
        result:""
    },
    UserLoginDefeated:{
        code:"10005",
        message:"用户登录失败",
        result:""
    },
    UserPasswordDefeated:{
        code:"10006",
        message:"用户密码错误",
        result:""
    },
    tokenExpiredError:{
        code:"10101",
        message:"token已过期",
        result:""
    },
    jsonWebTokenError:{
        code:"10102",
        message:"无效的token",
        result:""
    },
    UserPasswordRepeat:{
        code:"10103",
        message:"用户密码重复",
        result:""
    },
    NullToken:{
        code:"10104",
        message:"用户未登录",
        result:""
    },
    NotHadAdminPermission:{
        code:"10105",
        message:"没有管理员权限",
        result:""
    },
    fileUploadErr:{
        code:"10201",
        message:"上传失败",
        result:""
    },
    unSupportedType:{
        code:"10202",
        message:"不支持的文件格式",
        result:""
    },
    goodsFormatError:{
        code:"10203",
        message:"商品参数格式错误",
        result:""
    },
    PublishGoodsError:{
        code:"10204",
        message:"发布商品失败",
        result:""
    },
    updateGoodsDefine:{
        code:"10205",
        message:"修改商品失败",
        result:""
    },
    findGoodsIdDefine:{
        code:"10206",
        message:"未找到商品的id",
        result:""
    },
    cartFormatErr:{
        code:'10301',
        message:"购物车格式校验错误",
        result:""
    },
    addrFormatErr:{
        code:'10401',
        message:"地址数据格式校验错误",
        result:""
    },
    orderFormatError:{
        code:'10501',
        message:'商铺数据格式校验错误',
        result:""
    }
   
    
}